nextflow.enable.dsl=2

/*
 * =========================================================================================
 * Process: PLASMID_FINDER
 * =========================================================================================
 * Description:
 * Executes ABRicate using the PlasmidFinder database to detect and type plasmids within 
 * assembled contigs. Sorts the resulting hits by percent coverage and percent identity 
 * descending. Includes robust fallbacks for missing/empty assemblies or execution 
 * failures, guaranteeing a safely formatted tabular output to prevent pipeline crashes.
 *
 * Input:
 * - val(sid)         : Unique string identifier for the sample.
 * - path(contigs_fa) : Assembled contigs (FASTA format).
 *
 * Output:
 * - path("*_plasmidfinder.tab") : The ABRicate detection results table (or placeholder).
 * - path("*.plasmidfinder.log") : Execution log capturing stdout and stderr.
 * - emit: tab                   : Tuple of (sid, plasmidfinder_tab).
 * - emit: log                   : The execution log file.
 *
 * Exceptions & Fallbacks:
 * - Empty Contigs / Skipped Assembly: If the input FASTA is empty or contains the 
 * "NO_ASSEMBLY_INSUFFICIENT_READS" flag, exits 0 and emits a placeholder table.
 * - Execution Failure: If ABRicate fails or produces empty output, safely falls back 
 * to emitting a valid placeholder table with a NO_PLASMID_RESULT flag.
 */
process PLASMID_FINDER {
  tag "${sid}"
  publishDir "${params.outdir ?: 'results'}/abricate/${sid}", mode: 'copy', overwrite: true

  input:
    tuple val(sid), path(contigs_fa)

  output:
    tuple val(sid), path("${sid}_plasmidfinder.tab"), emit: tab
    path("${sid}.plasmidfinder.log"),                  emit: log

  script:
  def dbdir   = params.abricate_db_dir ?: ''
  def dbname  = params.abricate_db_plasmidfinder ?: 'plasmidfinder'
  def minid   = params.abricate_minid ?: 75
  def mincov  = params.abricate_mincov ?: 60

  def header = "#FILE\tSEQUENCE\tSTART\tEND\tSTRAND\tGENE\tCOVERAGE\tCOVERAGE_MAP\tGAPS\t%COVERAGE\t%IDENTITY\tDATABASE\tACCESSION\tPRODUCT"

  """
  set -euo pipefail

  out="${sid}_plasmidfinder.tab"
  log="${sid}.plasmidfinder.log"

  write_no_result () {
    reason="\$1"
    echo "${header}" > "\$out"
    echo -e "${sid}\\tNO_ASSEMBLY\\t0\\t0\\tNA\\tNO_PLASMID_RESULT\\t0/0\\tNA\\t0\\t0\\t0\\tplasmidfinder\\tNA\\t\${reason}" >> "\$out"
    {
      echo "[PLASMID_FINDER] WARNING: \${reason}"
      echo "[PLASMID_FINDER] sample=${sid}"
      echo "[PLASMID_FINDER] contigs=${contigs_fa}"
    } > "\$log"
  }

  if [ ! -s "${contigs_fa}" ]; then
    write_no_result "Empty contigs file"
    exit 0
  fi

  if grep -q "NO_ASSEMBLY_INSUFFICIENT_READS" "${contigs_fa}"; then
    write_no_result "No valid assembly: insufficient reads after cleaning"
    exit 0
  fi

  {
    abricate \\
      -db ${dbname} \\
      --datadir ${dbdir} \\
      --minid ${minid} \\
      --mincov ${mincov} \\
      ${contigs_fa} > "\$out"

    if [ ! -s "\$out" ]; then
      write_no_result "ABRicate produced empty output"
      exit 0
    fi

    # Sort by %COVERAGE (col 10) then %IDENTITY (col 11), preserving header.
    {
      head -n 1 "\$out"
      tail -n +2 "\$out" | sort -t \$'\\t' -k10,10nr -k11,11nr
    } > "\$out.sorted"

    mv "\$out.sorted" "\$out"

  } &> "\$log" || {
    echo "${header}" > "\$out"
    echo "WARN: abricate failed for ${sid}" >> "\$log"
  }
  """
}

/*
 * =========================================================================================
 * Process: PLASMID_FINDER_COLLECT
 * =========================================================================================
 * Description:
 * Aggregates individual plasmid detection tables generated by PLASMID_FINDER into a 
 * unified, project-level summary using a custom Python script (plasmid_collect.py). 
 * Includes safeguards to ensure a valid output file is always generated even if the 
 * collection step encounters an error or receives empty inputs.
 *
 * Input:
 * - path(tabs) : A collected list of all individual *_plasmidfinder.tab files.
 *
 * Output:
 * - path("plasmidfinder_all.tab")     : The aggregated summary table.
 * - path("plasmidfinder_collect.log") : Execution log for the collation script.
 * - emit: tab                         : Named emission for the aggregated table.
 * - emit: log                         : Named emission for the collection log.
 *
 * Exceptions & Fallbacks:
 * - Script Failure / Empty Output: If the custom Python collection script crashes or 
 * produces an empty file, catches the error and writes a valid, header-only 
 * placeholder table to maintain downstream compatibility.
 */
process PLASMID_FINDER_COLLECT {
  publishDir "${params.outdir ?: 'results'}/abricate", mode: 'copy', overwrite: true

  input:
    path tabs

  output:
    path "plasmidfinder_all.tab", emit: tab
    path "plasmidfinder_collect.log", emit: log

  """
  set -euo pipefail

  if python3 ${projectDir}/bin/plasmid_collect.py \\
      --inputs ${tabs} \\
      --output plasmidfinder_all.tab \\
      > plasmidfinder_collect.log 2>&1; then

    if [ ! -s plasmidfinder_all.tab ]; then
      echo "[PLASMID_FINDER_COLLECT] Empty output; writing placeholder header" >> plasmidfinder_collect.log
      echo -e "#FILE\\tSEQUENCE\\tSTART\\tEND\\tSTRAND\\tGENE\\tCOVERAGE\\tCOVERAGE_MAP\\tGAPS\\t%COVERAGE\\t%IDENTITY\\tDATABASE\\tACCESSION\\tPRODUCT" > plasmidfinder_all.tab
    fi

  else
    echo "[PLASMID_FINDER_COLLECT] plasmid_collect.py failed; writing placeholder header" >> plasmidfinder_collect.log
    echo -e "#FILE\\tSEQUENCE\\tSTART\\tEND\\tSTRAND\\tGENE\\tCOVERAGE\\tCOVERAGE_MAP\\tGAPS\\t%COVERAGE\\t%IDENTITY\\tDATABASE\\tACCESSION\\tPRODUCT" > plasmidfinder_all.tab
  fi
  """
}