/*
 * =========================================================================================
 * Process: TB_PROFILER
 * =========================================================================================
 * Description:
 * Executes TB-Profiler to determine lineage and predict antimicrobial resistance 
 * profiles for Mycobacterium tuberculosis samples. It includes multiple taxonomic 
 * and upstream execution checks to ensure it only processes valid, decontaminated 
 * inputs. Generates placeholder outputs if bypassed to maintain downstream channels.
 *
 * Input:
 * - val(sample_id)      : Unique string identifier for the sample.
 * - path(counts_tsv)    : The decontamination counts file emitted by CLOCKWORK.
 * - path(r1)            : Forward decontaminated reads from CLOCKWORK.
 * - path(r2)            : Reverse decontaminated reads from CLOCKWORK.
 * - val(mash_id)        : Taxonomic classification string derived from prior MASH step.
 *
 * Output:
 * - val(sample_id)                             : Unique sample identifier.
 * - path("results/${sample_id}.results.csv")   : Sample CSV report (native or placeholder).
 * - path("results/${sample_id}.results.json")  : Sample JSON report (native or placeholder).
 * - emit: tb_results                           : Named emission channel for the above tuple.
 *
 * Exceptions & Fallbacks:
 * - Non-target Organism: Exits 0 and emits placeholders if mash_id lacks 'mycobacterium'.
 * - Upstream Skip: Exits 0 and emits placeholders if CLOCKWORK was skipped.
 * - Execution Failure: Exits 0 and emits placeholders if tb-profiler profile fails.
 * - Missing Output: Exits 0 and emits placeholders if expected files are empty/missing.
 */
process TB_PROFILER {
  publishDir "${params.outdir}/TB_Profiler", mode: 'copy'
  tag { sample_id }

  input:
  tuple val(sample_id),
        path(counts_tsv),
        path(r1),
        path(r2),
        val(mash_id)

  output:
  tuple val(sample_id),
        path("results/${sample_id}.results.csv"),
        path("results/${sample_id}.results.json"),
        emit: tb_results

  script:
  """
  set -euo pipefail

  mkdir -p results

  write_placeholder_outputs () {
    reason="\$1"

    echo "[TB_PROFILER] WARNING: \${reason} for ${sample_id}" >&2

    cat > "results/${sample_id}.results.csv" <<EOF
sample_id,status,mash_id,lineage,drug_resistance,reason
${sample_id},SKIPPED_TB_PROFILER,${mash_id},NA,NA,"\${reason}"
EOF

    cat > "results/${sample_id}.results.json" <<EOF
{
  "sample_id": "${sample_id}",
  "status": "SKIPPED_TB_PROFILER",
  "mash_id": "${mash_id}",
  "lineage": "NA",
  "drug_resistance": "NA",
  "reason": "\${reason}"
}
EOF
  }

  mash_lc="\$(echo "${mash_id}" | tr '[:upper:]' '[:lower:]')"

  if [ -z "\${mash_lc}" ] || [ "\${mash_lc}" = "na" ] || [ "\${mash_lc}" = "no_mash_hit" ]; then
    write_placeholder_outputs "No Mycobacterium Mash hit"
    exit 0
  fi

  if ! echo "\${mash_lc}" | grep -q "mycobacterium"; then
    write_placeholder_outputs "Mash ID is not Mycobacterium"
    exit 0
  fi

  if grep -q "SKIPPED_CLOCKWORK" "${counts_tsv}"; then
    write_placeholder_outputs "Clockwork was skipped"
    exit 0
  fi

  if ! tb-profiler profile \\
    -1 ${r1} \\
    -2 ${r2} \\
    --csv \\
    -t ${task.cpus} \\
    -p ${sample_id} \\
    --dir .; then

    write_placeholder_outputs "TBProfiler failed"
    exit 0
  fi

  if [ ! -s "results/${sample_id}.results.csv" ] || [ ! -s "results/${sample_id}.results.json" ]; then
    write_placeholder_outputs "TBProfiler output missing"
    exit 0
  fi
  """
}

/*
 * =========================================================================================
 * Process: TB_PROFILER_COLLATE
 * =========================================================================================
 * Description:
 * Aggregates individual TB-Profiler CSV outputs into a single, combined summary table 
 * specifically formatted for ingestion by MultiQC. It also attempts to run the native 
 * tb-profiler collate command to generate broader project-level reports, but isolates 
 * that step to prevent pipeline failure if the native collation crashes.
 *
 * Input:
 * - path(tb_files) : A collected list of all results/* files emitted by TB_PROFILER.
 *
 * Output:
 * - path("tbprofiler.txt") : A stable, custom TSV summary explicitly built for MultiQC.
 * - path("tbprofiler*")    : A glob catch-all for any native reports generated by collate.
 * - emit: tbprofiler_txt     : Named emission for the custom MultiQC TSV.
 * - emit: tbprofiler_rollups : Named emission for the native aggregated outputs.
 *
 * Exceptions & Fallbacks:
 * - Native Collate Failure: Does not crash workflow. Prints warning and proceeds.
 * - No Samples Found: Generates a NO_SAMPLE row to prevent MultiQC parser errors.
 * - Glob Safety: Creates a dummy tbprofiler_summary.txt if native collate produces nothing,
 * ensuring the output channel requirement is satisfied.
 */
process TB_PROFILER_COLLATE {
  publishDir "${params.outdir}/TB_Profiler", mode: 'copy'

  input:
  path(tb_files, stageAs: 'results/*')

  output:
  path "tbprofiler.txt", emit: tbprofiler_txt
  path "tbprofiler*", emit: tbprofiler_rollups

  script:
  """
  set -euo pipefail

  # MultiQC-friendly custom content table.
  # This file is intentionally simple and stable.
  echo -e "sample\\tstatus\\tmash_id\\tmain_lineage\\tsub_lineage\\tdrtype\\treason" > tbprofiler.txt

  found_any=0

  for csv in results/*.results.csv; do
    [ -f "\$csv" ] || continue
    found_any=1

    sample=\$(basename "\$csv" .results.csv)

    # Placeholder CSV from our TB_PROFILER process:
    # sample_id,status,mash_id,lineage,drug_resistance,reason
    if grep -q "SKIPPED_TB_PROFILER" "\$csv"; then
      tail -n +2 "\$csv" | awk -F',' -v s="\$sample" 'BEGIN{OFS="\\t"} {
        gsub(/"/, "", \$6)
        print s,\$2,\$3,\$4,"NA",\$5,\$6
      }' >> tbprofiler.txt
    else
      # Native TBProfiler CSVs can vary by version.
      # Keep a stable status row for MultiQC; native collate below preserves details if it succeeds.
      echo -e "\${sample}\\tTB_PROFILER_COMPLETE\\tNA\\tNA\\tNA\\tNA\\tNative TBProfiler CSV generated" >> tbprofiler.txt
    fi
  done

  if [ "\$found_any" -eq 0 ]; then
    echo -e "NO_SAMPLE\\tNO_TBPROFILER_INPUT\\tNA\\tNA\\tNA\\tNA\\tNo TBProfiler CSV files found" >> tbprofiler.txt
  fi

  # Try native TBProfiler collate, but do not let it kill the pipeline.
  if tb-profiler collate --dir results; then
    echo "[TB_PROFILER_COLLATE] Native tb-profiler collate completed" >&2
  else
    echo "[TB_PROFILER_COLLATE] WARNING: native tb-profiler collate failed; using tbprofiler.txt summary" >&2
  fi

  # Ensure at least one extra tbprofiler* rollup exists for the broad output glob.
  if ! ls -1 tbprofiler* >/dev/null 2>&1; then
    cp tbprofiler.txt tbprofiler_summary.txt
  fi
  """
}