
/*
 * =========================================================================================
 * Process: EL_GATO_RUN
 * =========================================================================================
 * Description:
 * Executes the El Gato typing tool to determine the Sequence Type (ST) and allele 
 * profile for Legionella pneumophila samples. Features robust error handling that 
 * prevents pipeline crashes if the native tool exits with a non-zero status. It 
 * strictly normalizes all outputs into a 9-column TSV format required by the 
 * downstream MultiQC custom content parser, padding with placeholders if necessary.
 *
 * Input:
 * - val(sample_id) : Unique string identifier for the sample.
 * - path(r1)       : Forward cleaned reads.
 * - path(r2)       : Reverse cleaned reads.
 *
 * Output:
 * - path("*.el_gato.tsv") : Normalized 9-column TSV allele report (or placeholder).
 * - emit (implicit)       : Tuple of (sample_id, el_gato_tsv).
 *
 * Exceptions & Fallbacks:
 * - Tool Failure: execution uses `set +e` to catch native tool crashes. If it fails 
 * or produces an empty/missing file, the awk parser safely generates a 9-column NA 
 * placeholder row.
 * - Format Validation: Performs a hard check on column counts before exiting to 
 * guarantee MultiQC compatibility.
 */
process EL_GATO_RUN {
  tag { sample_id }

  publishDir "${params.outdir ?: 'results'}/el_gato",
             mode: 'copy',
             overwrite: true

  cpus { params.elgato_cpus ?: 2 }

  input:
    tuple val(sample_id), path(r1), path(r2)

  output:
    tuple val(sample_id), path("${sample_id}.el_gato.tsv")

  script:
    def exe = params.elgato_exe ?: 'el_gato.py'
    def t   = task.cpus as int

    """
    set -euo pipefail

    SAMPLE="${sample_id}"
    R1="${r1}"
    R2="${r2}"
    EXE="${exe}"
    CPUS=${t}

    OUTFILE="\${SAMPLE}.el_gato.tsv"
    OUTDIR="\${SAMPLE}.elgato"
    TMPSTDOUT="el_gato.stdout.txt"

    printf "sample\\tST\\tflaA\\tpilE\\tasd\\tmip\\tmompS\\tproA\\tneuA\\n" > "\${OUTFILE}"

    echo "[EL_GATO] Running for \${SAMPLE} (cpus=\${CPUS})" >&2
    echo "[EL_GATO] exe=\${EXE}" >&2
    echo "[EL_GATO] r1=\${R1}" >&2
    echo "[EL_GATO] r2=\${R2}" >&2

    # Run tool, but do not kill the pipeline if El Gato exits nonzero.
    set +e
    "\${EXE}" \\
      --read1 "\${R1}" \\
      --read2 "\${R2}" \\
      --out "\${OUTDIR}" \\
      > "\${TMPSTDOUT}" 2> el_gato.stderr.txt
    ec=\$?
    set -e

    echo "[EL_GATO] exit_code=\${ec}" >&2

    # Prefer canonical result file if El Gato created one.
    if [ -s "\${OUTDIR}/results_summary.tsv" ]; then
      cp "\${OUTDIR}/results_summary.tsv" "\${TMPSTDOUT}"
    fi

    # Normalize El Gato output to exactly 9 tab-delimited columns:
    # sample, ST, flaA, pilE, asd, mip, mompS, proA, neuA
    if [ -s "\${TMPSTDOUT}" ]; then
      awk -F '\\t' -v OFS='\\t' -v sample="\${SAMPLE}" '
        BEGIN {
          wrote = 0
        }

        length(\$0) == 0 {
          next
        }

        tolower(\$1) == "sample" {
          next
        }

        tolower(\$1) == "st" {
          next
        }

        NF == 8 {
          print sample, \$1, \$2, \$3, \$4, \$5, \$6, \$7, \$8
          wrote = 1
          next
        }

        NF >= 9 {
          print \$1, \$2, \$3, \$4, \$5, \$6, \$7, \$8, \$9
          wrote = 1
          next
        }

        NF > 0 {
          print sample, \$1, "-", "-", "-", "-", "-", "-", "-"
          wrote = 1
          next
        }

        END {
          if (wrote == 0) {
            print sample, "NA", "-", "-", "-", "-", "-", "-", "-"
          }
        }
      ' "\${TMPSTDOUT}" >> "\${OUTFILE}"
    fi

    # Ensure at least one data row exists.
    if [ "\$(wc -l < "\${OUTFILE}" | tr -d ' ')" -eq 1 ]; then
      printf "%s\\tNA\\t-\\t-\\t-\\t-\\t-\\t-\\t-\\n" "\${SAMPLE}" >> "\${OUTFILE}"
    fi

    # Hard validation for MultiQC custom content.
    awk -F '\\t' '
      NF != 9 {
        print "[EL_GATO_RUN] Bad column count: " NF " :: " \$0 > "/dev/stderr"
        exit 1
      }
    ' "\${OUTFILE}"

    ls -lh "\${OUTFILE}" >&2 || true
    test -s "\${OUTFILE}"
    """
}

/*
 * =========================================================================================
 * Process: EL_GATO_COLLECT
 * =========================================================================================
 * Description:
 * Aggregates individual El Gato TSV reports generated by EL_GATO_RUN into a unified, 
 * project-level summary table (el_gato_combined.tsv). Enforces a secondary layer of 
 * strict awk-based column count validation to ensure the final aggregated file will 
 * not crash the downstream MultiQC parser.
 *
 * Input:
 * - path(tsvs) : A collected list of all individual *.el_gato.tsv files.
 *
 * Output:
 * - path("el_gato_combined.tsv") : The aggregated 9-column summary table.
 *
 * Exceptions & Fallbacks:
 * - Malformed Inputs: If any aggregated row contains an unexpected number of columns, 
 * the awk script pads it or substitutes "UNKNOWN_SAMPLE" to maintain structural integrity.
 * - Bad Final Count: Exits 1 if the final combined file violates the 9-column rule.
 */
process EL_GATO_COLLECT {
  tag "el_gato_combined"

  publishDir "${params.outdir ?: 'results'}/el_gato",
             mode: 'copy',
             overwrite: true

  input:
    path(tsvs)

  output:
    path("el_gato_combined.tsv")

  script:
    def tsv_list = tsvs.join(' ')
    """
    set -euo pipefail

    printf "sample\\tST\\tflaA\\tpilE\\tasd\\tmip\\tmompS\\tproA\\tneuA\\n" > el_gato_combined.tsv

    for f in ${tsv_list}; do
      [ -s "\$f" ] || continue

      tail -n +2 "\$f" | awk -F '\\t' -v OFS='\\t' '
        NF >= 9 { print \$1,\$2,\$3,\$4,\$5,\$6,\$7,\$8,\$9; next }
        NF == 8 { print "UNKNOWN_SAMPLE",\$1,\$2,\$3,\$4,\$5,\$6,\$7,\$8; next }
        NF > 0  { print \$1,"NA","-","-","-","-","-","-","-"; next }
      ' >> el_gato_combined.tsv
    done

    awk -F '\\t' 'NF != 9 { print "[EL_GATO_COLLECT] Bad column count:", NF, \$0 > "/dev/stderr"; exit 1 }' el_gato_combined.tsv
    """
}

/*
 * =========================================================================================
 * Workflow: EL_GATO
 * =========================================================================================
 * Description:
 * Main entry point for the Legionella typing sub-workflow. Joins the cleaned read 
 * channel with the MASH taxonomic species classification channel. It acts as a router, 
 * strictly filtering the channel to pass ONLY confirmed Legionella samples (or samples 
 * manually tagged with "LEG" in their ID) into the EL_GATO_RUN process.
 *
 * Take:
 * - reads_ch   : Channel emitting tuple(sample_id, r1, r2).
 * - species_ch : Channel emitting tuple(sample_id, species_txt) from MASH.
 *
 * Emit:
 * - per_sample : Channel emitting individual El Gato TSV results.
 * - combined   : Channel emitting the unified el_gato_combined.tsv.
 */
workflow EL_GATO {
  take:
    reads_ch
    species_ch

  main:
    legionella_reads = reads_ch
      .join(species_ch)
      .map { sid, r1, r2, species_txt ->
        def sp = species_txt.text.trim()
        ( (sp =~ /(?i)\blegionella\b/) || (sid =~ /(?i)LEG/) )
          ? tuple(sid, r1, r2)
          : null
      }
      .filter { it != null }

    elgato_out = EL_GATO_RUN(legionella_reads)

    EL_GATO_COLLECT(
      elgato_out
        .map { sid, tsv -> tsv }
        .collect()
    )

  emit:
    per_sample = elgato_out
    combined   = EL_GATO_COLLECT.out
}