nextflow.enable.dsl=2

/*
 * =========================================================================================
 * Process: BWA_READMETRICS
 * =========================================================================================
 * Description:
 * Calculates read mapping metrics from a sorted BAM file. Includes robust validations 
 * to detect missing files, empty alignments (header-only BAMs), or native script execution 
 * failures. In any failure state, it generates a safely formatted placeholder TSV to 
 * maintain pipeline continuity and ensure the collection step does not fail.
 *
 * Input:
 * - val(sample_id)             : Unique string identifier for the sample.
 * - path(alignment_sorted_bam) : The sorted BAM file generated by upstream mapping.
 *
 * Output:
 * - path("*.bam.readMetrics.tsv") : The read metrics summary table (or placeholder).
 * - path("*.bam.readMetrics.log") : Execution log capturing samtools counts and stderr.
 * - emit: tsv                     : Tuple of (sample_id, metrics_tsv).
 * - emit: log                     : The execution log file.
 *
 * Exceptions & Fallbacks:
 * - Missing/Empty BAM: Exits 0 and emits NO_ALIGNMENT placeholder if BAM is missing/empty.
 * - Zero Alignments: Safely queries BAM with samtools; if count is 0, emits placeholder.
 * - Execution Failure: Exits 0 and emits placeholder if run_assembly_readMetrics.pl crashes.
 * - Empty Output Validation: Exits 0 and emits placeholder if the final TSV is empty.
 */
process BWA_READMETRICS {
  tag { sample_id }
  publishDir "${params.outdir}/bwa", mode: 'copy', overwrite: true, pattern: "*bam.readMetrics.tsv"

  input:
    tuple val(sample_id), path(alignment_sorted_bam)

  output:
    tuple val(sample_id), path("${sample_id}.bam.readMetrics.tsv"), emit: tsv
    path("${sample_id}.bam.readMetrics.log"), emit: log

  shell:
  '''
  set -euo pipefail

  out="!{sample_id}.bam.readMetrics.tsv"
  raw="!{sample_id}.bam.readMetrics.raw.tsv"
  err="!{sample_id}.bam.readMetrics.err"
  log="!{sample_id}.bam.readMetrics.log"

  write_placeholder () {
    reason="$1"
    {
      echo "[BWA_READMETRICS] WARNING: ${reason}"
      echo "[BWA_READMETRICS] sample=!{sample_id}"
      echo "[BWA_READMETRICS] bam=!{alignment_sorted_bam}"
    } > "$log"

    cat > "$out" <<EOF
sample_id	status	total_reads	mapped_reads	note
!{sample_id}	NO_ALIGNMENT	0	0	${reason}
EOF
  }

  echo "[BWA_READMETRICS] bam: !{alignment_sorted_bam}" > "$log"
  ls -lh "!{alignment_sorted_bam}" >> "$log" 2>&1 || true

  if [ ! -s "!{alignment_sorted_bam}" ]; then
    write_placeholder "missing_or_empty_bam"
    exit 0
  fi

  # If samtools is available, detect BAMs with zero alignments.
  if command -v samtools >/dev/null 2>&1; then
    n_align=$(samtools view -c "!{alignment_sorted_bam}" 2>> "$log" || echo 0)
    echo "[BWA_READMETRICS] alignment_count=${n_align}" >> "$log"

    if [ "${n_align}" -eq 0 ]; then
      write_placeholder "header_only_or_zero_alignment_bam"
      exit 0
    fi
  fi

  if run_assembly_readMetrics.pl --fast --numcpus !{task.cpus} -e 5000000 "!{alignment_sorted_bam}" \
      > "$raw" \
      2> "$err"; then

    {
      head -n 1 "$raw"
      tail -n +2 "$raw" | sort -k3,3n
    } > "$out"

    if [ ! -s "$out" ]; then
      write_placeholder "readMetrics_produced_empty_output"
      exit 0
    fi

    cat "$err" >> "$log" || true

  else
    cat "$err" >> "$log" || true
    write_placeholder "readMetrics_failed"
    exit 0
  fi
  '''
}


/*
 * =========================================================================================
 * Process: BWA_READMETRICS_COLLECT
 * =========================================================================================
 * Description:
 * Concatenates individual BAM read metric TSV files generated by BWA_READMETRICS into a 
 * unified, single-file summary table. This aggregated file is highly useful for overall 
 * project reporting and direct ingestion into tools like MultiQC.
 *
 * Input:
 * - path(metric_tsvs) : A collected list of 1 or more individual metric TSVs.
 *
 * Output:
 * - path("bam.readMetrics_all.tsv") : The aggregated summary table.
 * - emit: tsv                       : Named emission for the aggregated TSV.
 *
 * Exceptions & Fallbacks:
 * - No Inputs Provided: If the input array is entirely empty, safely generates a dummy 
 * file with proper headers and a "NO_SAMPLE" row to prevent downstream parser errors.
 */
process BWA_READMETRICS_COLLECT {
  publishDir "${params.outdir ?: 'results'}/bwa", mode: 'copy', overwrite: true, pattern: "bam.readMetrics_all.tsv"
  cpus 1
  memory '1 GB'

  input:
    path metric_tsvs, arity: '1..*'

  output:
    path "bam.readMetrics_all.tsv", emit: tsv

  shell:
  '''
  set -euo pipefail

  echo "[COLLECT] TSVs: !{metric_tsvs}"

  files=( !{metric_tsvs} )

  if [[ ${#files[@]} -eq 0 ]]; then
    echo -e "sample_id\tstatus\ttotal_reads\tmapped_reads\tnote" > bam.readMetrics_all.tsv
    echo -e "NO_SAMPLE\tNO_INPUT_FILES\t0\t0\tNo metric TSVs were provided" >> bam.readMetrics_all.tsv
    exit 0
  fi

  head -n 1 "${files[0]}" > bam.readMetrics_all.tsv

  for f in "${files[@]}"; do
    tail -n +2 "$f" >> bam.readMetrics_all.tsv || true
  done
  '''
}